export const EMAIL_REGEX = /[^@ \t\r\n]+@[^@ \t\r\n]+\.[^@ \t\r\n]+/;

export const DEFAULT_AVATAR = "/avatar.webp";

export const LANGUAGES = [
  "English",
  "Mandarin Chinese",
  "Spanish",
  "Hindi",
  "Arabic",
  "Bengali",
  "Portuguese",
  "Russian",
  "Urdu",
  "Indonesian",
  "French",
  "German",
  "Japanese",
  "Swahili",
  "Turkish",
  "Italian",
  "Dutch",
  "Korean",
  "Telugu",
  "Marathi",
  "Tamil",
  "Vietnamese",
  "Yoruba",
  "Thai",
  "Persian",
  "Punjabi",
  "Malayalam",
  "Javanese",
  "Wu Chinese",
  "Filipino",
];

export const THINGS_TO_EXPECT = [
  "Learn creative skills to achieve your personal and professional goals.",
  "Tune in and level up at your own pace.",
  "Go from dabbler to master in a matter of hours.",
  "Connect with a global community of curious creatives.",
];

export const DUMMY_COURSES = [
  {
    title: "intro to Programming",
    rating: 5,
    noOfStudents: 1123,
    duration: "11hrs",
    image: "bg-learn-one",
  },
  {
    title: "Creative Writing",
    rating: 5,
    noOfStudents: 1123,
    duration: "11hrs",
    image: "bg-learn-two",
  },
  {
    title: "Artificial Inteligence",
    rating: 5,
    noOfStudents: 1123,
    duration: "11hrs",
    image: "bg-learn-four",
  },
  {
    title: "Marketting Marvel",
    rating: 5,
    noOfStudents: 1123,
    duration: "11hrs",
    image: "bg-learn-five",
  },
  {
    title: "Millionaire in a day",
    rating: 5,
    noOfStudents: 1123,
    duration: "11hrs",
    image: "bg-learn-eight",
  },
  {
    title: "Music Production",
    rating: 5,
    noOfStudents: 1123,
    duration: "11hrs",
    image: "bg-learn-seven",
  },
  {
    title: "video editing",
    rating: 5,
    noOfStudents: 1123,
    duration: "11hrs",
    image: "bg-learn-four",
  },
  {
    title: "Cooking 101",
    rating: 5,
    noOfStudents: 1123,
    duration: "11hrs",
    image: "bg-learn-one",
  },
  {
    title: "Dance",
    rating: 5,
    noOfStudents: 1123,
    duration: "11hrs",
    image: "bg-learn-two",
  },
  {
    title: "Movie Production",
    rating: 5,
    noOfStudents: 1123,
    duration: "11hrs",
    image: "bg-learn-seven",
  },

  {
    title: "Forex",
    rating: 5,
    noOfStudents: 1123,
    duration: "11hrs",
    image: "bg-learn-seven",
  },

  {
    title: "import and export",
    rating: 5,
    noOfStudents: 1123,
    duration: "11hrs",
    image: "bg-learn-seven",
  },
  {
    title: "Youtubing",
    rating: 5,
    noOfStudents: 1123,
    duration: "11hrs",
    image: "bg-learn-seven",
  },
  {
    title: "Arts and culture",
    rating: 5,
    noOfStudents: 1123,
    duration: "11hrs",
    image: "bg-learn-seven",
  },
  {
    title: "Flavours ",
    rating: 5,
    noOfStudents: 1123,
    duration: "11hrs",
    image: "bg-learn-seven",
  },
  {
    title: "Public speaking",
    rating: 5,
    noOfStudents: 1123,
    duration: "11hrs",
    image: "bg-learn-seven",
  },
];
